package Resources;

public enum ResourceName {
    IS_VARTOTOJO_SASAJOS,
    SUPERVIZORINE_ATMINTIS,
    UZDUOTIS_SUPERVIZORINEJE_ATMINTYJE,
    EILUTE_ATMINTYJE,
    UZDUOTIES_VYKDYMO_PARAMETRAI_SUPERVIZORINEJE_ATMINTYJE,
    UZDUOTIES_PROGRAMA_SUPERVIZORINEJE_ATMINTYJE,
    ISORINE_ATMINTIS,
    KANALU_IRENGINYS,
    UZDUOTIS_BUGNE,
    IS_LOADER,
    VARTOTOJO_ATMINTIS,
    NEEGZISTUOJANTIS,
    MOS_PABAIGA;
}
